### ISSUE TITLE
Convergence error when using run_time_response function

### ISSUE THREAD

**Issue by Raimundovpn** [petrobras/ross#1001]
When running the run_time_response function lsim, the integrator is not converging, resulting in NaN values:

![image](https://github.com/petrobras/ross/assets/96801225/184d182c-9689-4e66-896f-a8ea34de3d83)

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
Currently, we are not able to reproduce this issue.
I will close it for now and if we come across this error again we can reopen it.
