### ISSUE TITLE
Drop support for older versions of python

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#1007]
We should drop the support for older python versions and add the new python versions to the test matrix.
The idea is to follow the following as a guide: [Recommend Python and NumPy version support](https://numpy.org/neps/nep-0029-deprecation_policy.html).

Therefore, we should drop support for python 3.7 and 3.8, and add python 3.11 to our test matrix.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
