### ISSUE TITLE
Change folder name: defects for malfunctions

### ISSUE THREAD

**Issue by ViniciusTxc3** [petrobras/ross#1013]
In the literature, in rotordynamics, I see the term "malfunctions" being used more than "defects". I suggest changing the "defects" > "malfunctions" folder. The word defects gives the impression of something wrong with the files inside.

![image](https://github.com/petrobras/ross/assets/42445116/d2770392-04e9-4a73-a7b6-4ee482a51ee3)

@raphaeltimbo what do you think?

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by jguarato** [comment]
As discussed, we actually chose to replace defects for faults. So, I submitted the necessary modifications in PR #1060.
