### ISSUE TITLE
Calculation of diametral inertia

### ISSUE THREAD

**Issue by lilian-tec** [petrobras/ross#1024]
Hello, 

I have a definition problem with the diametral moment of inertia.
How is it calculated?

`disk1 = rs.DiskElement.from_geometry(
    n=4,
    material=steel,
    width=0.07,
    i_d=0.05,
    o_d=0.28
)`

> Mass           (kg):      32.59
Diam. inertia  (kg*m**2): 0.17809
Polar. inertia (kg*m**2): 0.32956

Re-creating the geometry in a CAD model, you get

> Ix = 0.2180116989456501 # kg.m2
Iy = 0.2180116989456501 # kg.m2
Iz = 0.3295636208913719 # kg.m2

I suppose you get Id from Ix and Iy but cannot found out how, my guess was that Id = Ix = Iy

Thank you!

**Comment by lilian-tec** [comment]
Very sorry I intended to post this in Discussions.
I did now ( --> https://github.com/petrobras/ross/discussions/1025 )
This should be deleted

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
