### ISSUE TITLE
Rotor summary

### ISSUE THREAD

**Issue by PetterTh** [petrobras/ross#1042]
Hi, and thank you for a very useful package!

I have two issues I want to address both regarding the rotor.summaryResults

First, it seems like the rotor.summaryResults collects the wrong nodes for the discs. The nodal position uses the bearing nodes and not the disc nodes:
```
        disk_data = {
            "Tag": self.df_disks["tag"],
            "Shaft number": self.df_disks["shaft_number"],
            "Node": self.df_disks["n"],
            "Nodal Position": self.nodes_pos[self.df_bearings["n"]],
            "Mass": self.df_disks["m"].map("{:.3f}".format),
            "Ip": self.df_disks["Ip"].map("{:.3e}".format),
        }
```
I think this can be solved by changing to
`"Nodal Position": self.nodes_pos[self.df_disks["n"]],`

Secondly, when I have linked bearings the code fails as self.nodes does not contain the position of the nodes not on the shaft.
Using the example at https://ross.readthedocs.io/en/stable/user_guide/tutorial_part_1.html#creating-a-rotor-model
adding 
```
summary=rotor1.summary()
fig=summary.plot()
```
gives the error

>   File "C:\Users\XXXXX\Anaconda3\envs\ross\Lib\site-packages\ross\results.py", line 4141, in plot
>     "Nodal Position": self.nodes_pos[self.df_bearings["n"]],
>                       ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
> IndexError: index 7 is out of bounds for axis 0 with size 7

**Comment by jguarato** [comment]
Hi @PetterTh,

Thank you for your feedback and for bringing these issues to our attention.

You are correct regarding `disk_data`. It should indeed be `"Nodal Position": self.nodes_pos[self.df_disks["n"]]`. 
Regarding the second error, it is related to the node position of linked bearings.

I've already fixed these issues in PR #1047. However, it is under review to be merged into the main branch of the project.
