### ISSUE TITLE
Start migration from black to ruff

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#1044]
Ruff now has the autoformat capabilities. We should start migrating from black to ruff.
https://docs.astral.sh/ruff/faq/#how-does-ruffs-formatter-compare-to-black

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
