### ISSUE TITLE
Fix bearing stiffness for compressor example

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#1058]
The bearings used to assemble the compressor example that we have in our tutorials is not correct:

![image](https://github.com/petrobras/ross/assets/18506378/0c6752b2-b085-4986-a4ca-9e3d2b56f327)

**Comment by ViniciusTxc3** [comment]
@raphaeltimbo, We're working on a PR to update the plot, with the change of rotor_example_compressor, I got the following result:

![image](https://github.com/petrobras/ross/assets/42445116/d1b4db46-1104-4a35-a22c-44abf4e240eb)

**Comment by raphaeltimbo** [comment]
Solved in #1071.
