### ISSUE TITLE
Update numpy

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#1072]
Numpy released v2.0.0, but this version is incompatible with some libraries.
For now we are restricting numpy to <2.0.0 and in the future we will revisite this issue.

**Comment by jguarato** [comment]
It appears that in NumPy 2.0.0, the representation `repr` of NumPy scalars changed, causing conflicts when running pytest.
See: [NumPy 2.0.0 Release Notes](https://numpy.org/devdocs/release/2.0.0-notes.html#representation-of-numpy-scalars-changed)
