### ISSUE TITLE
Tutorial 3: TypeError: 'Probe' object is not subscriptable

### ISSUE THREAD

**Issue by jamesgarvey93** [petrobras/ross#1093]
In following [tutorial part 3](https://ross.readthedocs.io/en/latest/user_guide/tutorial_part_3.html), I get a TypeError: 'Probe' object is not subscriptable within ST_ForcedResponseResults.plot >> ST_ForcedResponseResults.plot_magnitude (see below traceback). The input was copied verbatim from the example page.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 fig3 = results.plot(probe=[Probe(3, np.pi/2)], conf_interval=[90], mag_kwargs=dict(yaxis=dict(type="log")))
      2 fig3.show()

File ~/ross/ross/stochastic/st_results.py:2187, in ST_ForcedResponseResults.plot(self, probe, percentile, conf_interval, probe_units, frequency_units, amplitude_units, phase_units, mag_kwargs, phase_kwargs, polar_kwargs, subplot_kwargs)
   2184 subplot_kwargs = {} if subplot_kwargs is None else copy.copy(subplot_kwargs)
   2186 # fmt: off
-> 2187 fig0 = self.plot_magnitude(
   2188     probe, percentile, conf_interval, probe_units, frequency_units, amplitude_units, None, **mag_kwargs
   2189 )
   2190 fig1 = self.plot_phase(
   2191     probe, percentile, conf_interval, probe_units, frequency_units, amplitude_units, phase_units, None, **phase_kwargs
   2192 )
   2193 fig2 = self.plot_polar_bode(
   2194     probe, percentile, conf_interval, probe_units, frequency_units, amplitude_units, phase_units, None, **polar_kwargs,
   2195 )

File ~/ross/ross/stochastic/st_results.py:1715, in ST_ForcedResponseResults.plot_magnitude(self, probe, percentile, conf_interval, probe_units, frequency_units, amplitude_units, fig, **kwargs)
   1712 color_p = 0
   1714 for i, p in enumerate(probe):
-> 1715     angle = Q_(p[1], probe_units).to("rad").m
   1716     vector = self._calculate_major_axis_per_node(
   1717         node=p[0], angle=angle, amplitude_units=amplitude_units
   1718     )[:, 1, :]
   1719     try:

TypeError: 'Probe' object is not subscriptable

**Comment by jguarato** [comment]
Hi @jamesgarvey93!

Thank you for reporting this issue. The `Probe` class is being used in Tutorial 3, but there is no handling for its use in the ROSS stochastic module. We've just addressed this issue in PR #1095, and the correction will be available soon. 

For now, if you want to continue testing the tutorial, you can remove `Probe`. For example:
```python
fig3 = results.plot(probe=[(3, np.pi/2)], conf_interval=[90], mag_kwargs=dict(yaxis=dict(type="log")))
...
fig4 = results.plot_1d(probe=[(3, np.pi / 2)], conf_interval=[90])
```
