### ISSUE TITLE
Create ShaftElement from multiple 'sub elements'

### ISSUE THREAD

**Issue by atbrandao** [petrobras/ross#412]
In order to better control the L/D ratio of each Shaft Element in rotors that have multiple diameter changes within a short axial length, it is useful to be able to create one single shaft element from different sub-elements.

The figure below shows an example of a rotor section created on XLTRC2 in which 2 shaft elements, represented in different colors, are created using 5 different sub-elements: the first element has 2 sub-elements and the second has 3 sub-elements.

![image](https://user-images.githubusercontent.com/44202099/72152610-48511c00-338a-11ea-9584-cfbafdf12c5c.png)

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
