### ISSUE TITLE
Proportional damping

### ISSUE THREAD

**Issue by verg1lio** [petrobras/ross#532]
This issue is intended for the discussion and decision on how (and if...) to implement the proportional damping coefficients "alpha" and "beta" on the code. 

Currently it is made as an shaft_element property, and can be chosen arbitrarily as a adjustment parameter for fine tuning the model. Another proposition is to make it a material property, and give suggestions to the user as to an "standard" range for the values.

**Comment by rodrigomoliveira1** [comment]
I agree.

We could add &alpha; and &beta; parameters for both, material and shaft element. And then, adding to global damping matrix like:

![\mathbf C = \sum_{j=1}^{N_{mat}} \[\alpha_j^m \mathbf M_j + \beta_j^m \mathbf K_j\] + \sum_{i=1}^{N_{e}} \[\alpha_i^e \mathbf M_i + \beta_i^e \mathbf K_i\]](https://render.githubusercontent.com/render/math?math=%5Cmathbf%20C%20%3D%20%5Csum_%7Bj%3D1%7D%5E%7BN_%7Bmat%7D%7D%20%5B%5Calpha_j%5Em%20%5Cmathbf%20M_j%20%2B%20%5Cbeta_j%5Em%20%5Cmathbf%20K_j%5D%20%2B%20%5Csum_%7Bi%3D1%7D%5E%7BN_%7Be%7D%7D%20%5B%5Calpha_i%5Ee%20%5Cmathbf%20M_i%20%2B%20%5Cbeta_i%5Ee%20%5Cmathbf%20K_i%5D)

Where, the first sum is the proportional damping related to the material properties of each element, and the second one, related to the element itself.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by RodrigoTanajura** [comment]
We are studying how (and if) we will implement this issue once again.

**Comment by raphaeltimbo** [comment]
This has been implemented in the ShaftElement6DoF class.
