### ISSUE TITLE
Try to calculate/estimate displacements and forces based on measured vibrations

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#704]
Currently, industrial machines typically have vibrations sensors in two axial positions in the rotor which are normally close to the bearings. This means that we only have 'eyes' on those positions, and we cannot know exactly what is happening in other parts of the rotor.
In each axial position we have 2 vibration probes that are placed 90 degrees from each other, and this makes possible to get the displacement orbit for that area of the shaft.
It would be very useful to have some functionality in ROSS that would enable us to calculate/estimate vibrations and forces in every position of our rotor based on informations we have from vibration measurements in these positions and the model we have with ROSS.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
