### ISSUE TITLE
Some tutorials/examples are not showing cells outputs

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#759]
As an example:
https://ross-rotordynamics.github.io/ross-website/examples/tutorial_part_2.html
![image](https://user-images.githubusercontent.com/18506378/108356076-682c5380-71ca-11eb-9aa0-a249e57d7198.png)

**Comment by rodrigomoliveira1** [comment]
At first, I thought it was caused due the lack of `.show()` command in the end of the line. But if we look to other examples from [tutorial part 1](https://ross-rotordynamics.github.io/ross-website/examples/tutorial_part_1.html), it shows the image without it.

![image](https://user-images.githubusercontent.com/45969994/108357327-0b319d00-71cc-11eb-9856-a8cc69389e59.png)

**Comment by raphaeltimbo** [comment]
For some reason notebooks will not always store the plots, so we have to execute them during the build process.
I have opened a PR implementing this.

**Comment by raphaeltimbo** [comment]
I am reopening this issue since the plots are not showing again.

**Comment by raphaeltimbo** [comment]
After migrating things to readthedocs I was still having this problem in some notebooks.
Just to register here, in one case I had to import plotly:
```python
import plotly.graph_objects as go
```
Even though I was not calling plotly directly in the notebook (was only the `rotor.plot_rotor()` method).

**Comment by raphaeltimbo** [comment]
Once again we have this problem in the Modeling tutorial.
Will check what is happening.

**Comment by raphaeltimbo** [comment]
Solved the current issue by trusting the notebooks, adding the following to the imports and rerunning:

```python
import plotly.graph_objects as go
import plotly.io as pio

pio.renderers.default = "notebook"
```

**Comment by raphaeltimbo** [comment]
Reopen this on for the pages below:

- [ ] Overview
- [ ]

**Comment by ViniciusTxc3** [comment]
Waiting for #1040 to be solved for this issue.
