### ISSUE TITLE
Mode shape tracking and identification for the Campbell diagram

### ISSUE THREAD

**Issue by verg1lio** [petrobras/ross#821]
Dear all, good afternoon! (@raphaeltimbo , @elyqg , @hiagopinacio)

This issue is a proposition for an enhancement of the Campbell diagram's capabilities, attending to what was discussed previously in a Petrobrás - EDGE meeting. The requirements asked are:

1 - ability to identify the mode shapes in an automated manner (_i.e._ is the mode a lateral one? axial? torsional?);
2 - ability to track the modes if they suffer crossing over or veering phenomena, without mixing them up.

The first is a "quality of life" improvement, and aids in the evaluation of mechanical systems. The second is needed especially in the case of 6 _DoF_ models, since lateral and torsional or lateral and axial modes tend to interact and present said phenomena.

After evaluation of current methodologies and viable manners to achieve these goals, I suggest we follow the proposed by the annexed article below. I will be busy in the near future developing this formulation and applying it to a known system, in order to verify its validity and code consistency. This will be done via a dedicated PR in our [https://github.com/LMEst-Rotor/ross](url) branch.

[ACriterionforModeShapeTracking-ApplicationtoCampbellDiagrams.pdf](https://github.com/ross-rotordynamics/ross/files/6779098/ACriterionforModeShapeTracking-ApplicationtoCampbellDiagrams.pdf)

**Comment by verg1lio** [comment]
The pseudo-code is as follows:

![image](https://user-images.githubusercontent.com/57490973/124813660-85747b00-df3b-11eb-93e4-f20bfc60f701.png)

**Comment by raphaeltimbo** [comment]
Ok, @verg1lio ! I will be assigning the issue to you. 

PS.: don't worry about using 'WIP' in issues, we only use it in PRs to avoid merging work that it is not complete.

**Comment by verg1lio** [comment]
> Ok, @verg1lio ! I will be assigning the issue to you.
> 
> PS.: don't worry about using 'WIP' in issues, we only use it in PRs to avoid merging work that it is not complete.

Thank you @raphaeltimbo , and I'll remember that too.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
Identification of modes has been solved in #1066;
