### ISSUE TITLE
Add Probe class

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#827]
Currently we use list of tuples to add probes to our results.
The problem is that, contrary to other parts of ROSS, we are not able to use pint.Quantity to the probe orientation.
Instead, we have to declare the unit in a separate argument:

```
        probe : list
            List with tuples (node, orientation angle, tag).

            node : int -> Indicate the node where the probe is located.

            orientation : float -> Probe orientation angle about the shaft.
            The 0 refers to +X direction.
            The strings 'major' and 'minor' can also be used to reference the major
            and minor axis.

            tag : str, optional -> Probe tag to be add a DataFrame column title.
        probe_units : str, option
            Units for probe orientation.
            Default is "rad".
```

With a probe class we would be able to do something like:

```python
probe_la = rs.Probe(15, Q_(45, 'deg'))
```

Another possibility would be to add filter (1x etc.) to the probe.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
