### ISSUE TITLE
Argument L is missing in the ShaftElement docstring

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#914]
Argument L is missing in the ShaftElement docstring.

**Comment by raphaeltimbo** [comment]
Hi @marcusfilipesr! 
Since this is a very small fix I don't see a problem in doing that.
Just be sure to link that PR with this issue here (write `Closes #914` in the PR message).

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
