### ISSUE TITLE
Digits for damping ratio in plot_mode_3d

### ISSUE THREAD

**Issue by LeifParr** [petrobras/ross#932]
Hi all. I still haven't gotten around to setting up for contributing, so therefore I kindly ask of you a little suggestion:
When plotting modes in 3d, using damping ratio, 1 digit of resolution is not sufficient.

In ross 1.3.0, this is located in results.py, line 1115, function plot_mode_3d:
                    f"{damping_name} = {damping_value:.1f}"
could be changed to
                    f"{damping_name} = {damping_value:.2f}"

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
