### ISSUE TITLE
Change Campbell axis units

### ISSUE THREAD

**Issue by marcusfilipesr** [petrobras/ross#973]
`ROSS` displays the Campbell diagram with the default unit as `rad/s` in both axis, i.e., the natural frequencies is in `rad/s` and also the rotor speed.

However, in the literature the diagram is shown with `y` with `hertz (hz)`, and the `x` with `rpm`. Maybe, could we set this parameters as default? Additionally, we could split the `frequency_units` into two variables for the `x` and `y` axis.

**Comment by ViniciusTxc3** [comment]
We will change the scale as rpm  default but keep both axes  with the same units.
