### ISSUE TITLE
Migrate benchmark codes

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#978]
We have some codes for ross benchmark in this repository: https://github.com/ross-rotordynamics/ross-benchmark

We should migrate this code to a 'benchmark' folder within the main ross repository and update the code so that it works with our current code base.

**Comment by ViniciusTxc3** [comment]
@raphaeltimbo , I started a PR #983 to migrate the files, but I have some doubts :

1. Do we create the "/Snakeviz_inputs" folders and the "Benchmarks" model outside of ross or inside the benchmark folder?
2. Can we include the snakeviz library in the general requirements.txt or just the .[dev]?
3. Should we create a `Benchmark()` class that contains a run method to make it easier for the user to execute?
