### ISSUE TITLE
Some tests are failing for python 3.10

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#991]
Action run example at: https://github.com/petrobras/ross/actions/runs/5448234119/jobs/9911193630?pr=983

**Comment by marcusfilipesr** [comment]
I'll will look into this!

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ViniciusTxc3** [comment]
@raphaeltimbo these failing tests also happened in version 3.9, due to some test tolerances that were low, mainly in docstrings. I believe that updates to the Scipy library may have created these differences. I created a PR #1014  that tries to fix it.
