### ISSUE TITLE
Update tutorials

### ISSUE THREAD

**Issue by raphaeltimbo** [petrobras/ross#995]
The tutorials are a little behind regarding the ROSS development.
I think we could address some points:

- [ ] Divide tutorial 1 (modeling) and 2 (running analyzes) in more parts. They are long, making it harder to follow, find subjects and load time is high due to several plots in one notebook;
- [ ] We could simplify the documentation by removing some parts. Example: Creating elements from excel, creating elements using 'from_sections' etc. These are not the main way to use the package and having them in the tutorial make it harder for a new user to go through the documentation (we should move these to a dedicated doc);
- [ ] Highlight more the use of the main functions to save and load ross objects using .toml files. In the tutorial 2 (running analyzes) for example we load a rotor using excel files, but we should load using a .toml file;
- [ ] Replace the bearing coefficients for the rotor used in the tutorial 2 (running analyzes). The model that we have in the repository has coefficients that were calculated with an outdated software and they give a strange plot in the ucs results.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by raphaeltimbo** [comment]
Solved in #1071.
