### ISSUE TITLE
Error regarding the transformation matrix used in converting the angle of the probes in ROSS plots and calculations.

### ISSUE THREAD

**Issue by stanley-washington** [petrobras/ross#999]
When adjusting the angle of the probes in the ross, a transformation matrix called 'operator' is used. However, it has an error:

![image](https://github.com/petrobras/ross/assets/63065882/e6a1ad39-fe86-48a7-a243-d91e489d0f12)

And the correct form should be:

![image](https://github.com/petrobras/ross/assets/63065882/a18c4903-b2ef-4506-8bb4-40bc0a5154d1)

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by ViniciusTxc3** [comment]
These matrices are also in the _abs_defect.py_ and _st_results.py_ files, in addition to _results.py_. I created PR #1002 to make this correction.

**Comment by raphaeltimbo** [comment]
Hi @ViniciusTxc3 and @stanley-washington 
I think we should recheck this issue based on discussion #1033.
@stanley-washington, could you provide some reference for the modification proposed here?
Also, we should add some tests to verify the values that we get from run_time_response depending on probe orientation so that we have this part of the code covered.

**Comment by raphaeltimbo** [comment]
Some tasks related to this issue:

- [ ] Extract the probe response calculation from the plot method and create a probe_response method;
- [ ] Probe response method should return a dataframe with time column and response column for each probe passed in the list;
- [ ] Add test for probe_response method.

```python
def probe_response(self, probe):
    ...
    return probe_response

def plot_1d(self, probe, ...):
    ...
    probe_response = self.probe_response(probe)
    ...
    fig.add_scatter(
        x=probe_response["t"]
        y=probe_response["probe_y"]
```

**Comment by stanley-washington** [comment]
The operation described entails rotating the predicted displacement values based on the angle specified by the argument probe (_p[1]_). This rotation is achieved using a transformation matrix, denoted as _T_, where the _X_ and _Y_ coordinate axes are rotated accordingly. However, there's an issue with the implementation of the transformation matrix _T_ in the API, as evidenced in lines 4440-4444 of the '_results.py_' file.

![image](https://github.com/petrobras/ross/assets/63065882/b0a9bbcd-1db1-447b-97b8-c82a9419e822)

![image](https://github.com/petrobras/ross/assets/63065882/d8851dbb-5124-4482-9ae6-27e4ac7c40fa)

Currently, the operation simultaneously calculates the rotated values for both the _X_ and _Y_ axes. However, for the purpose of visualizing the signal rotated with respect to the probe, it suffices to consider only the rotation of the _X_ axis.

Furthermore, a sum-of-squares operation on the _X_ and _Y_ values is being performed, which is unnecessary for the intended purpose. Consequently, this step can be omitted from the procedure.

In view of this, I believe that the correct form for the code would be as follows:

![image](https://github.com/petrobras/ross/assets/63065882/b673f5c7-04d0-407f-b918-cab12c587d35)

**Comment by ViniciusTxc3** [comment]
@stanley-washington @raphaeltimboI created a PR for this fix.
I ran the example and the result was this:

```python
probe1 = (3, 0)   # node 3, orientation 0° (X dir.)
probe2 = (3, 90)  # node 3, orientation 90°(Y dir.)
probe3 = (3, 45)  # node 3, orientation 45°(Y dir.)

response3.plot_1d(probe=[probe1, probe2, probe3], probe_units="degree").show()
```

![image](https://github.com/petrobras/ross/assets/42445116/35390902-73e7-4224-a816-5fa5beca7bd1)

Now, I will work on the method to return the dataframe and tests.

**Comment by ViniciusTxc3** [comment]
@raphaeltimbo I updated PR #1037, with the suggested items:

- [x] Extract the probe response calculation from the plot method and create a probe_response method;
- [x] Probe response method should return a dataframe with time column and response column for each probe passed in the list;
- [x] Add test for probe_response method.

The new intermediate method is called `data_probe_response()`.
